Repository googleapis/nodejs-tasks, pull requests merged in 2019-05, with the labels that each got.

#208 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#209 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#210 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#213 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#215 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#214 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#212 build: switches to piping coverage to codecov from Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#216 docs: updating to latest proto docs
  src/v2/cloud_tasks_client.js
  src/v2/doc/google/iam/v1/doc_iam_policy.js
  src/v2/doc/google/iam/v1/doc_policy.js
  src/v2/doc/google/type/doc_expr.js
  src/v2beta2/cloud_tasks_client.js
  src/v2beta2/doc/google/iam/v1/doc_iam_policy.js
  src/v2beta2/doc/google/iam/v1/doc_policy.js
  src/v2beta2/doc/google/type/doc_expr.js
  src/v2beta3/cloud_tasks_client.js
  src/v2beta3/doc/google/iam/v1/doc_iam_policy.js
  src/v2beta3/doc/google/iam/v1/doc_policy.js
  src/v2beta3/doc/google/type/doc_expr.js
  synth.metadata
Labels: cla: yes

#217 fix: DEADLINE_EXCEEDED no longer treated as idempotent and retried
  src/v2/cloud_tasks_client_config.json
  src/v2beta2/cloud_tasks_client_config.json
  src/v2beta3/cloud_tasks_client_config.json
  synth.metadata
Labels: cla: yes

#219 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v2/cloud_tasks_client_config.json
  src/v2beta2/cloud_tasks_client_config.json
  src/v2beta3/cloud_tasks_client_config.json
  synth.metadata
Labels: cla: yes

#220 docs: update jsdoc formatting and tests
  protos/google/cloud/tasks/v2beta3/cloudtasks.proto
  protos/google/cloud/tasks/v2beta3/queue.proto
  protos/google/cloud/tasks/v2beta3/target.proto
  protos/google/cloud/tasks/v2beta3/task.proto
  src/v2beta3/cloud_tasks_client.js
  src/v2beta3/doc/google/cloud/tasks/v2beta3/doc_cloudtasks.js
  src/v2beta3/doc/google/cloud/tasks/v2beta3/doc_queue.js
  src/v2beta3/doc/google/cloud/tasks/v2beta3/doc_target.js
  src/v2beta3/doc/google/cloud/tasks/v2beta3/doc_task.js
  synth.metadata
  test/gapic-v2beta3.js
Labels: cla: yes

#221 docs: generate docs for ga release
  .repo-metadata.json
  README.md
  package.json
  protos/google/cloud/tasks/v2/cloudtasks.proto
  protos/google/cloud/tasks/v2/queue.proto
  protos/google/cloud/tasks/v2/target.proto
  protos/google/cloud/tasks/v2/task.proto
  protos/google/cloud/tasks/v2beta3/cloudtasks.proto
  protos/google/cloud/tasks/v2beta3/target.proto
  samples/README.md
  samples/quickstart.js
  samples/test/test.samples.js
  src/v2/cloud_tasks_client.js
  src/v2/doc/google/cloud/tasks/v2/doc_cloudtasks.js
  src/v2/doc/google/cloud/tasks/v2/doc_target.js
  src/v2beta3/cloud_tasks_client.js
  src/v2beta3/doc/google/cloud/tasks/v2beta3/doc_target.js
  synth.metadata
Labels: cla: yes

#222 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#223 chore: remove unused repo-tools dependency and cleanup
  .cloud-repo-tools.json
  package.json
Labels: cla: yes

#225 docs(samples): Update ReadMe and comments for samples
  samples/README.md
  samples/createHttpTask.js
  samples/createHttpTaskWithToken.js
  samples/createTask.js
  samples/quickstart.js
  samples/server.js
Labels: cla: yes

#226 docs: update readme to match quickstart
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#230 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#232 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v2/cloud_tasks_client.js
  src/v2beta2/cloud_tasks_client.js
  src/v2beta3/cloud_tasks_client.js
  synth.metadata
Labels: cla: yes

#233 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#234 build: add configuration for automated doc deployemnt
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#235 chore: do not require projectId env for sample tests
  package.json
  samples/test/test.samples.js
Labels: cla: yes

#236 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#237 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
