Repository googleapis/nodejs-tasks, pull requests merged in 2020-11, with the labels that each got.

#482 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudtasks, cla: yes, context: full

#484 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v2/cloud_tasks_client.ts
  src/v2beta2/cloud_tasks_client.ts
  src/v2beta3/cloud_tasks_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudtasks, automerge, cla: yes

#486 fix(browser): check for fetch on window
  protos/protos.json
  src/v2/cloud_tasks_client.ts
  src/v2beta2/cloud_tasks_client.ts
  src/v2beta3/cloud_tasks_client.ts
  synth.metadata
Labels: api: cloudtasks, cla: yes, context: none

#489 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full
