Repository googleapis/nodejs-tasks, pull requests merged in 2020-10, with the labels that each got.

#465 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#466 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: cloudtasks, automerge: exact, cla: yes, context: full

#472 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#474 docs(samples): add region tags for sample browser
  samples/createQueue.js
  samples/deleteQueue.js
  samples/listQueues.js
Labels: cla: yes

#475 docs(samples): update samples to latest standards
  samples/createHttpTask.js
  samples/createHttpTaskWithToken.js
  samples/createQueue.js
  samples/createTask.js
  samples/deleteQueue.js
  samples/listQueues.js
  samples/package.json
  samples/quickstart.js
Labels: cla: yes

#476 fix(samples): region tag collided with tasks-api
  samples/createTask.js
  samples/quickstart.js
Labels: cla: yes

#473 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#478 docs: update to sample in readme
  README.md
  synth.metadata
Labels: cla: yes, context: none

#481 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: automerge, cla: yes, context: full
