Repository googleapis/nodejs-tasks, pull requests merged in 2020-07, with the labels that each got.

#432 chore: update gitattributes and ignore
  .gitattributes
  .gitignore
  synth.metadata
Labels: cla: yes, context: partial

#433 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#434 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#437 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#439 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#440 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#441 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#443 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#444 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#446 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:run

#448 build: configuration for new doc site
  .kokoro/release/docs-devsite.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
