Repository googleapis/nodejs-tasks, pull requests merged in 2020-06, with the labels that each got.

#419 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#422 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v2/cloud_tasks_client.ts
  src/v2beta2/cloud_tasks_client.ts
  src/v2beta3/cloud_tasks_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#425 fix: handle fallback option properly
  .kokoro/populate-secrets.sh
  src/v2/cloud_tasks_client.ts
  src/v2beta2/cloud_tasks_client.ts
  src/v2beta3/cloud_tasks_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#426 feat: introducing field Queue.type docs: fixing typos and minor updates
  protos/google/cloud/tasks/v2beta3/cloudtasks.proto
  protos/google/cloud/tasks/v2beta3/queue.proto
  protos/google/cloud/tasks/v2beta3/target.proto
  protos/google/cloud/tasks/v2beta3/task.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: full

#427 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#430 build: add gitattribute
  .gitattributes
  .gitignore
Labels: cla: yes
